FROM python:3.10-slim

ENV PYTHONUNBUFFERED=1 \
    PATH="/root/.local/bin:$PATH" \
    PYTHONPATH="/"

WORKDIR /app

COPY pyproject.toml poetry.lock ./

RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        curl \
        gcc \
        python3-dev \
        libpq-dev && \
    curl -sSL https://install.python-poetry.org | python3 - --yes && \
    poetry config virtualenvs.create false && \
    poetry install --no-root && \
    poetry add gunicorn && \
    apt-get remove -y curl gcc && \
    apt-get autoremove -y && \
    apt-get clean && \
    rm -rf /var/lib/apt/lists/* && \
    mkdir -p migrations/versions && \
    chmod -R 777 migrations/versions

COPY . .

EXPOSE 8000

CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "main:app", "--bind", "0.0.0.0:8000"]