FROM python:3.10-slim

ENV PYTHONUNBUFFERED=1
ENV PATH="/root/.local/bin:$PATH"
ENV PYTHONPATH="/"

RUN apt-get update && apt-get install -y curl gcc python3-dev libpq-dev && apt-get clean
RUN curl -sSL https://install.python-poetry.org | python3 - --yes
RUN poetry --version
RUN poetry config virtualenvs.create false

COPY pyproject.toml poetry.lock /

RUN poetry install --no-root
RUN poetry add gunicorn
RUN apt-get remove -y curl && apt-get autoremove -y && apt-get clean
RUN mkdir -p /app/migrations/versions && chmod -R 777 /app/migrations/versions

COPY . .

WORKDIR /app
EXPOSE 8000

CMD ["gunicorn", "-k", "uvicorn.workers.UvicornWorker", "main:app", "--bind", "0.0.0.0:8000"]